### ISSUE TITLE
Getting the amount of revenue made for a certain period of time

### ISSUE THREAD

**Issue by gantonious** [gantonious/JobberSmartAssistant#13]
### Acceptance Criteria

- [x] AC-8.1: An admin should be able to determine the amount of revenue made by their company in a given unit of time using the Jobber API
- [x] AC-8.2: An admin who requests how much revenue their company has made without specifying the unit of time should get a response indicating how much money was made in the last week
- [x] AC-8.3: An admin who requests how much revenue their company has made within a specific unit of time should get a response indicating how much money was made within that unit of time
- [ ] AC-8.4: If the admin specifies a bad time unit then the assistant should re-prompt the admin to specify a valid time range
- [ ] AC-8.5: If the admin specifies a bad time unit 3 times in a row then the assistant should fall back to returning the amount of revenue made in the last week

**Comment by calho** [comment]
How should we deal with the 3 bad tries. I think the assistant will end conversation if given 3 unrecognizable inputs?

**Comment by gantonious** [comment]
Yeah Google Assistant automagically ends the conversation after 3 bad inputs.

**Comment by gantonious** [comment]
Is this closeable?

**Comment by calho** [comment]
Yeah this should be closable.
Don't really know if we can do AC-8.4 if we keep time unit as optional.
for AC-8.5 I think we mentioned that we can scrap it?

**Comment by gantonious** [comment]
Yeah let's scrap those last two.
