### ISSUE TITLE
Getting the total number of jobs assigned for the day

### ISSUE THREAD

**Issue by gantonious** [gantonious/JobberSmartAssistant#14]
### Acceptance Criteria

- [x] AC-9.1: An admin should be able to get the amount of jobs they have assigned to them that day using the Jobber API
- [x] AC-9.2: A field worker whose account has no jobs assigned to them should get a response along the lines of “Your day looks clear!”
- [x] AC-9.3: A field worker whose account has one job assigned to them should get a response informing them they have one job that day, who the job is for, where it is, and the time frame of the job.
- [x] AC-9.4: A field worker whose account has multiple jobs assigned to them should get a response informing them how many jobs they have for that day, who the first job is for, where it is, and the time frame of the first job.

**Comment by dai-dao** [comment]
solved
