### ISSUE TITLE
Getting how long their working day is

### ISSUE THREAD

**Issue by gantonious** [gantonious/JobberSmartAssistant#16]
### Acceptance Criteria:

- [x] AC-11.1: A field worker should be able to get how long their work day is by using the Jobber API
- [x] AC-11.2: When a field worker requests for how many hours are assigned to them for the day, the smart assistant should return the sum of each assigned job’s duration to them
- [x] AC-11.3: When a field worker request for how long their work day is, the smart assistant should tell them they have no jobs that day

**Comment by dai-dao** [comment]
solved

**Comment by dai-dao** [comment]
solved

**Comment by gantonious** [comment]
@dai-dao I just tested this out and it looks like the time is not getting converted properly. Unix time is in milliseconds but it looks like the time is getting treated as seconds. This is what is getting returned right now:

![image](https://user-images.githubusercontent.com/9062713/38219088-53490372-3691-11e8-913e-ee207fc094ee.png)
It would also make sense to add the unit of time when returning the length of the day. So like "2 hours long"
