### ISSUE TITLE
Getting information on next job

### ISSUE THREAD

**Issue by gantonious** [gantonious/JobberSmartAssistant#17]
### Acceptance Criteria

- [x] AC-12.1: A field worker should be able to get information on their next job using the Jobber API
- [x] AC-12.2: When a field worker requests for information on their next visit, and it has an important note, the smart assistant should return the next visit’s location, time frame, client, description of the visit, how far the location is from current location, and the important note associated  with the visit
- [x] AC-12.3: When a field worker requests for information on their next visit, and it has important notes, the smart assistant should return the next visit’s location, time frame, client, description of the visit, how far the location is from current location, and the important notes associated  with the visit
- [x] AC-12.4: When a field worker requests for information on their next visit, and it has no important notes, the smart assistant should return the next visit’s location, time frame, client, description of the visit, and how far the location is from current location
- [x] AC-12.5: When a field worker requests for information on their next visit, and there is no next job for the day, the smart assistant should inform them there is no more jobs for the day

**Comment by dai-dao** [comment]
solved

**Comment by gantonious** [comment]
@dai-dao Looks like the description field in a visits is often set to null. So when you ask for the next job you will often get a comma followed by nothing where the description should be:

![image](https://user-images.githubusercontent.com/9062713/38210490-d3f7e582-3674-11e8-8962-8b8e7077e456.png)

We should also be rendering the dates as times so like 5:30 pm instead of the epoch times. I think returning then notes might be a bit too much but that's up to you.
