### ISSUE TITLE
Fix timezone issues when processing dates

### ISSUE THREAD

**Issue by gantonious** [gantonious/JobberSmartAssistant#21]
DialogFlow will give you a date range without a timezone but gives you the request timezone. We should use the request timezone to determine the time zone the user is intending on using. Preferably it would be better to make all the methods in `FulfillmentRequest` that return `DateTime` and `DateTimeRange` objects to return those objects in the timezone of the request made.

**Comment by calho** [comment]
In regards to this issue, are we saying that if we give an input of like 2018-03-27 3:00:00 PM in our timezone, we would get back the epoch of 2018-03-27 3:00:00 PM in UTC?
