### ISSUE TITLE
Figure out how to limit Jobber API requests to a given date range

### ISSUE THREAD

**Issue by gantonious** [gantonious/JobberSmartAssistant#23]
@calho Found out that you can limit the `/jobs` endpoint to follow a where clause. We should try and figure out if we can use that to put a date range on the query to avoid huge page sizes in our results.

**Comment by calho** [comment]
Oh Nice! How did you manage that? @gantonious

**Comment by gantonious** [comment]
I didn't haha. I'm saying we should look into it :p

**Comment by dai-dao** [comment]
I asked Chris and he gave some examples

Example request:
`https://jobber-ondemand-capstone.herokuapp.com/api/visits/?where=%5Bstart_at%3C%3D1521093599%2Cend_at%3E%3D1521007200%2Cassigned_to_user%3D5%5D`

which is just:
`?where=[start_at<=1521093599,end_at>=1521007200,assigned_to_user=5]`

**Comment by dai-dao** [comment]
Another note is that the jobs can consist of multiple visits over a range of time. So for example, if we want to get the amount of work for a worker during the day, we should query 'visits' instead, not jobs
